name: Fetch HDNEA Token

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-token:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Fetch HDNEA Token
        env:
          COOKIE_JSON_URL: ${{ secrets.HDNEA_JSON_URL }}
        run: |

          echo "Fetching token..."

          response=$(curl -s "$COOKIE_JSON_URL")

          token=$(echo "$response" | jq -r '.[0].cookie' | sed 's/^__hdnea__=//')

          if [ -z "$token" ] || [ "$token" = "null" ]; then
            echo "Token fetch failed"
            exit 1
          fi

          echo "__hdnea__=$token" > fetch.txt
          echo "Token saved"

      - name: Update M3U File
        run: python append_hdnea_m3u.py

      - name: Commit and Push
        run: |

          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add fetch.txt channels.m3u

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "Auto update HDNEA token"
          git push
